name: drdt

recipe: pantheon

config:
  framework: wordpress
  site: drdt
  id: 24fd5eae-e272-431c-877b-95c6bbeff62e
  xdebug: true
  webroot: web
  php: '7.1'

proxy:
  node:
    # Setup a proxy for the node service to connect
    # to BrowserSync at https://drdt.lndo.site:3000/
    - bs-drdt.lndo.site:3000

services:
  # Spin up a node service so we can run gulp
  node:
    type: node:custom
    ssl: true
    overrides:
      services:
        ports:
          # expose port 3000 for BrowserSync
          - "3000:3000"
        # use a custom Docker image
        image: ataylorme/docker-node-advanced-wordpress-on-pantheon:latest

# Additional "lando" commands
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  google-chrome-stable:
    service: node
  backstop:
    service: node
  composer:
    service: appserver
  wp:
    service: appserver
    cmd: ./vendor/wp-cli/wp-cli/bin/wp
  composer-install:
    description: Install Composer dependencies
    cmd: ./bin/install-composer-dependencies.sh
    service: appserver
  gulp-build:
    description: Install npm dependencies and run gulp
    cmd: ./.circleci/build-gulp-assets.sh
    service: node
  wordhat:
    description: Run WordHat
    cmd: ./vendor/bin/behat --config=tests/behat/behat-lando.yml --strict
    service: appserver
  wordhat-commands:
    description: List WordHat commands
    cmd: ./vendor/bin/behat -dl --config=tests/behat/behat-lando.yml --strict
    service: appserver

# Automate build steps after every start
#events:
#  post-start:
#    # Run gulp every time node is started
#    - node: "cd $LANDO_MOUNT && ./.circleci/build-gulp-assets.sh"
#    # Run composer every time appserver is started
#    - appserver: "cd $LANDO_MOUNT && ./bin/install-composer-dependencies.sh"
