---
- hosts: virtualpress
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:
      - name: Update apt cache
        apt:
          update_cache: yes
      - name: Install software-properties-common
        apt:
          name: software-properties-common
          state: latest
      - name: Install common utilities
        apt:
          name: "{{ packages }}"
          state: latest
        vars:
          packages:
            - unzip
            - htop
            - nethogs
      - name: Install dos2unix
        apt:
          name: dos2unix
          state: latest
      - name: Update installed software to latest versions
        apt:
          upgrade: dist
      - name: Add Vagrant user to www-data group
        user:
          name: ubuntu
          groups: www-data
          append: yes
  roles:
    - mysql
    - apache
    - php
    - wp-cli
    - wordpress
    - redis
